[pytest]
pythonpath = .
testpaths = tests

asyncio_mode = auto

addopts =
    -v
    --strict-markers
    --cov=app
    --cov-report=term-missing
    --cov-report=html

markers =
    unit: unit tests
    integration: integration tests